# Generated by Django 2.2.4 on 2019-11-17 09:25

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='user',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fam', models.FloatField()),
                ('electricity', models.FloatField()),
                ('plastic', models.FloatField()),
                ('two_wheeler_no', models.FloatField()),
                ('two_wheeler_mlg', models.FloatField()),
                ('dist_2', models.FloatField()),
                ('four_wheeler_no', models.FloatField()),
                ('four_wheeler_mlg', models.FloatField()),
                ('dist_4', models.FloatField()),
                ('dist_train', models.FloatField()),
                ('dist_bus', models.FloatField()),
                ('trees', models.FloatField()),
                ('emission', models.FloatField()),
                ('timestamp', models.DateTimeField(default=datetime.datetime(2019, 11, 17, 9, 25, 2, 339187, tzinfo=utc))),
            ],
        ),
    ]
