# Generated by Django 2.2.4 on 2019-11-17 09:38

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 17, 9, 38, 12, 240873, tzinfo=utc)),
        ),
    ]
