# Generated by Django 2.2.4 on 2019-11-17 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191117_0319'),
    ]

    operations = [
        migrations.CreateModel(
            name='Emission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('electricity_emission', models.FloatField()),
                ('plastic_emission', models.FloatField()),
                ('two_wheeler_emission', models.FloatField()),
                ('four_wheeler_emission', models.FloatField()),
                ('train_emission', models.FloatField()),
                ('bus_emission', models.FloatField()),
                ('trees_absorption', models.FloatField()),
            ],
        ),
        migrations.DeleteModel(
            name='user',
        ),
    ]
